# Generated by Django 3.2.11 on 2022-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_index',
            name='system_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
